config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  get 'welcome/index' 
  resources :prospects
  root 'welcome#index'
 
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/prospect.rb
class Prospect < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/prospects_controller.rb
class ProspectsController < ApplicationController
    def index
        # @prospects = Prospect.all
        prospect = Prospect.all

        render json: prospect
    end
    
    def new
    end

    def create
        prospect = Prospect.new(prospect_params)
        render json: prospect
        # @prospect.save
        # redirect_to @prospect
    end

    def show
        @prospect = Prospect.find(params[:id])
    end


    private
    def prospect_params
        params.require(:prospect).permit(:first_name, :last_name, :email)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/prospects_helper.rb
module ProspectsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BackEnd</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/prospects/index.html.erb
<strong>List of All Prosepcts</strong><br>

<%= link_to "New Prospect", new_prospect_path %>
<table>
    <tr>
        <th>First Name</th>
        <th>Last Name</th>
        <th>Email</th>
    </tr>

    <% @prospects.each do |prospect| %>
    <tr>
        <td><%= prospect.first_name %></td>
        <td><%= prospect.last_name %></td>
        <td><%= prospect.email %></td>
        <td><%= link_to "Show", prospect_path(prospect)%></td>
    </tr>
<% end %>
</table>

app/views/prospects/new.html.erb
<h1>Prospect Sign Up</h1>

<!-- May need html tags such as <p></p> for a querySelect in the future. -->
<%= form_with scope: :prospect, url: prospects_path, local: true do |form| %>
    <%= form.label :"First Name" %><br>
    <%= form.text_field :first_name %><br> 

    <%= form.label :"Last Name" %><br>
    <%= form.text_field :last_name %><br>  

    <%= form.label :email %><br>
    <%= form.text_field :email %><br> 
    
    <%= form.submit %>
<% end %>

<%= link_to "See All Prospects", prospects_url %>

app/views/prospects/show.html.erb
<strong>Registered Prospect</strong><br />

<%= @prospect.first_name %><br />
<%= @prospect.last_name %><br />
<%= @prospect.email %><br />

<%= link_to "Back", prospects_path %>

app/views/welcome/index.html.erb
<h1>Welcome Page </h1>

<%= link_to "Prospect Sign Ups", controller: "prospects" %>